# Generated by Django 4.0.4 on 2022-08-06 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_idea_owner', models.BooleanField(default=False)),
                ('is_investor', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('sector', models.CharField(max_length=250)),
                ('cac_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdeaOwner',
            fields=[
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('occupation', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=60)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=60)),
                ('id_number', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('cac_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=60)),
                ('id_number', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('source_of_income', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('categories', models.CharField(choices=[('AG', 'Agriculture'), ('TE', 'Technology'), ('ED', 'Education'), ('MN', 'Manufacturing')], default='TE', max_length=15)),
                ('stages', models.CharField(choices=[('ID', 'Ideation Stage'), ('ST', 'Startup stage'), ('GR', 'Growth stage'), ('MT', 'Matured stage')], default='ID', max_length=25)),
                ('idea_details', models.TextField()),
                ('idea_pitch', models.FileField(upload_to='uploads/')),
                ('completion_timeline', models.DateField()),
                ('estimated_cost', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='findApp.ideaowner')),
            ],
        ),
    ]
